[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"  # or whatever your command is
  publish = "public"         # or "dist" depending on your project

[secrets]
  # Paths to skip scanning for secrets
  omit_paths = [
    "netlify/functions/tradeHandler.js",
    "netlify/functions/trade-not.js",
    "netlify/functions/trade-accept.js"
  ]

  # Optional: suppress certain variable names if needed
  omit_keys = ["SUPABASE_KEY", "SUPABASE_URL"]

  # Optional: disable scanning completely (not recommended)
  # enabled = false
