[build]
  publish = "public"
  functions = "netlify/functions"
[secrets]
  omit_paths = [
    "netlify/functions/tradeHandler.js",
    "netlify/functions/trade-not.js",
    "netlify/functions/trade-accept.js"
  ]
  omit_keys = ["SUPABASE_KEY", "SUPABASE_URL"]


